[build]
  functions = "./dist/netlify/functions"
  command = "npm run build"
  publish = "dist"

[dev]
  functions = "src/netlify/functions"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
